# Generated by Django 5.0.7 on 2024-07-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='week_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='employee_d282b326abdd4c8599084a7a84e85878', editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default='ad021888cde84ecd915ab26e9daa9c64', max_length=200, unique=True),
        ),
    ]
