# Generated by Django 5.0.7 on 2024-07-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_shift_week_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='employee_62971879060142fa82f3075d20281eae', editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default='e079c0fc7b814e06950f9932ba0f0514', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=200),
        ),
        migrations.AlterField(
            model_name='staffroster',
            name='weekly_off',
            field=models.TextField(blank=True, null=True),
        ),
    ]
